version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "task-service"
      POSTGRES_USER: "dayadanya"
      POSTGRES_PASSWORD: "dayadanya"
    ports:
      - "5433:5432"